version: '3.8'

services:
  robotics-academy:
    image: jderobot/robotics-academy:4.5.3.beta
    container_name: radi-4.5.3.beta
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "7164:7164"
      - "2303:2303"
      - "1905:1905"
      - "8765:8765"
      - "6080:6080"
      - "1108:1108"
      - "7163:7163"
      - "5901:5901"
      - "5900:5900"
    volumes:
      - type: bind
        source: ./
        target: /RoboticsAcademy
    tty: true
    stdin_open: true
