# Generated by Django 4.0.5 on 2023-01-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_add_exercise_config'),
        ('exercises', '0015_exercise_status'),
    ]

    operations = [
    ]
